Add admin page navigation & styling
odevpl/kodillameet pull request #1
Opened 2022-12-09 11:25 UTC by MarcinBieniek

2022-12-09 12:28 UTC, odevpl requested changes
Przejżyj projekt i pozamieniać nazwa_klasy na nazwa-klasy :D

2022-12-09 12:28 UTC, odevpl commented on app/src/modules/MessagesBox/MessagesBox.js
> +            <div className="message_div">
message_div?
jeśli message, to message :)

2022-12-09 12:28 UTC, odevpl commented on app/src/modules/MessagesBox/MessagesBox.js
> +        <div className="messages_box">
zwykle klasy robi się z myślnikiem, więc message-box

2022-12-09 12:28 UTC, odevpl commented on app/src/modules/MessagesBox/MessagesBox.js
> +const MessagesBox = () => {
Ten komponent nie był ogólnie częścią ticketu :P

2022-12-09 12:28 UTC, odevpl commented on app/src/modules/UsersBox/UsersBox.js
> +        <div className="users_box">
user-box

2022-12-11 21:26 UTC, MarcinBieniek commented on app/src/modules/MessagesBox/MessagesBox.js
> +const MessagesBox = () => {
Czy może ewentualnie zostać? Od teraz trzymam się już sztywno trello :)

2022-12-11 21:26 UTC, MarcinBieniek commented
Zmiany zrobione zgodnie z uwagami.

2022-12-12 14:53 UTC, odevpl approved these changes

2022-12-12 17:18 UTC, merged